spring:
  application:
    name: profile-service
  config:
    import: "optional:configserver:http://localhost:8088"
  data:
    mongodb:
      uri: mongodb+srv://kmnavoddilshan:EfxVFWxNLKmA4Pwk@cluster0.cdlujqw.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: profile
#      uri: mongodb+srv://adhisha:PKtO36pBRQPiLQAM@cluster0.zx5zfjo.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
#      database: profile


